#!/bin/bash
#Author: Dillon Yeh
#For initial commits to github (yes i am that lazy)

#ARGS
#$1, Origin of repository

git init;
git add \--all;
git commit \-m "Initial Commit";
git remote add origin "$1";
git push \-u origin master;

